version: '3'
services: 
    yuuki:
        image: yuukibot/devcontainer
        depends_on:
            - redis
        environment:
            # Overrides your configs Redis options for use with Docker Compose
            #  I don't advise changing this unless you have a strange setup.
            - REDIS_DOCKER_OVERRIDE=true
        volumes:
            # VSCode workspace mount.
            - ..:/workspace:cached
        # Needed for nested docker
        privileged: true
    redis:
        image: "redis:alpine"
        volumes:
            - redisdata:/data

volumes:
    redisdata:
