name: Docker test and publish to Package Registry

on:
    push:
      branches: '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: yuukiuser
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: yuukibot/yuukichan
          tag_with_ref: true
          add_git_labels: true
