name: Docker test build (Devcontainer)

on: [push, pull_request]

jobs:
  test-build-dev:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          env: |
            DOCKER_HOST=unix:///run/user/997/docker.sock
          context: .
          file: ./.devcontainer/Dockerfile
          platforms: linux/amd64
          builder: builder
          push: false
