name: Docker test build

on:
  push:
    branches: 
    - '*'

  pull_request:
    branches: 
    - '*'

jobs:
  test-build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          repository: yuukibot/yuukichan
          tag_with_ref: true
          add_git_labels: true
          push: false
