name: Docker test build

on:
    push:
      branches: '*'
    pull_request:
      branches: '*'

jobs:
    docker-build-test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Test building the Docker image
            run: docker build .
