name: RuboCop Linter

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  lint:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: RuboCop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build-test:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Test building the Docker image
        uses: docker/build-push-action@v1
        with:
          tag_with_ref: true
    
  build-and-publish-latest:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: yuuki-bot # Provide only Docker image name, tag will be automatically set to latest
        dockerfile: Dockerfile
  

